name: Run Scrappers

on:
  repository_dispatch:
    types: [run_scrappers]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file: [scrapper59.js, scrapper60.js, scrapper61.js, scrapper62.js, scrapper63.js]


    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps chromium

      - name: Run scraper & upload DB
        env:
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          GDRIVE_REFRESH_TOKEN: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
        run: |
          node --max-old-space-size=4096 ${{ matrix.file }}
